[package]
name = "leo-lang"
version = "1.6.2"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "The Leo programming language"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/leo"
keywords = [
  "aleo",
  "cryptography",
  "leo",
  "programming-language",
  "zero-knowledge"
]
categories = [ "compilers", "cryptography", "web-programming" ]
include = [ "Cargo.toml", "leo", "README.md", "LICENSE.md" ]
license = "GPL-3.0"
edition = "2021"

[workspace]
members = [
  "compiler/ast",
  "compiler/compiler",
  "compiler/core",
  "compiler/parser",
  "compiler/passes",
  "compiler/span",
  "docs/grammar",
  "errors",
  "leo/package",
  "tests/test-framework"
]

[workspace.dependencies.snarkvm]
version = "0.9.11"

[workspace.dependencies.snarkvm-console]
version = "0.9.11"

[lib]
path = "leo/lib.rs"

[[bin]]
name = "leo"
path = "leo/main.rs"

[features]
default = [ ]
ci_skip = [ "leo-compiler/ci_skip" ]
noconfig = [ ]

[dependencies.aleo]
version = "0.3.3"

[dependencies.leo-ast]
path = "./compiler/ast"
version = "1.6.2"

[dependencies.leo-compiler]
path = "./compiler/compiler"
version = "1.6.2"

[dependencies.leo-errors]
path = "./errors"
version = "1.6.2"

[dependencies.leo-package]
path = "./leo/package"
version = "1.6.2"

[dependencies.leo-parser]
path = "./compiler/parser"
version = "1.6.2"

[dependencies.leo-span]
path = "./compiler/span"
version = "1.6.2"

[dependencies.backtrace]
version = "0.3.67"

[dependencies.clap]
version = "4.1"
features = [ "derive", "env" ]

[dependencies.color-backtrace]
version = "0.5.1"

[dependencies.colored]
version = "2.0"

[dependencies.console]
version = "0.15.5"

[dependencies.dirs]
version = "4.0.0"

[dependencies.indexmap]
version = "1.9"
features = [ "serde" ]

[dependencies.lazy_static]
version = "1.4.0"

[dependencies.rand]
version = "0.8"

[dependencies.rand_core]
version = "0.6.4"

[dependencies.reqwest]
version = "0.11.14"
features = [ "blocking", "json", "multipart" ]

[dependencies.self_update]
version = "0.34.0"
features = [ "archive-zip" ]

[dependencies.serde]
version = "1.0"
features = [ "derive" ]

[dependencies.serde_json]
version = "1.0"

[dependencies.snarkvm]
workspace = true
features = [ "aleo-cli", "circuit", "console", "parallel" ]

[dependencies.sys-info]
version = "0.9.1"

[dependencies.toml]
version = "0.7"

[dependencies.tracing]
version = "0.1"

[dependencies.tracing-subscriber]
version = "0.3.16"
features = [ "fmt" ]

[dependencies.zip]
version = "^0.6"

[target."cfg(windows)".dependencies.ansi_term]
version = "0.12.1"

[dev-dependencies.assert_cmd]
version = "2.0.8"

[dev-dependencies.rusty-hook]
version = "0.11.2"

[dev-dependencies.test_dir]
version = "0.2.0"

[build-dependencies.walkdir]
version = "2"

[profile.release]
opt-level = 3
lto = "thin"
incremental = true

[profile.bench]
opt-level = 3
debug = false
rpath = false
lto = "thin"
incremental = true
debug-assertions = false

[profile.dev]
opt-level = 2
lto = "thin"
incremental = true

[profile.test]
opt-level = 2
lto = "thin"
incremental = true
debug = true
debug-assertions = true
